site_name: pymechtest
repo_url: https://github.com/FollowTheProcess/pymechtest
site_url: https://followtheprocess.github.io/pymechtest/
site_description: Python package to automate the boring bits of mechanical test data analysis!
site_author: Tom Fleet
use_directory_urls: false
nav:
  - Home: index.md
  - Getting Started:
      - Usage: getting_started/usage.md
      - Options: getting_started/options.md
plugins:
  - mkdocstrings:
      watch:
        - pymechtest
  - search
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
