site_name: pymechtest
repo_url: https://github.com/FollowTheProcess/pymechtest
site_url: https://followtheprocess.github.io/pymechtest/
site_description: Python package to automate the boring bits of mechanical test data analysis!
site_author: Tom Fleet
use_directory_urls: false
strict: true
nav:
  - Home: index.md
  - Getting Started:
      - Usage: getting_started/usage.md
      - Options: getting_started/options.md
      - Plot Curves: getting_started/plot.md
  - Contributing:
      - Help: contributing/help.md
      - How to: contributing/guide.md
  - Roadmap: roadmap.md
  - API:
      - Static Tests:
          - Tensile: api/tensile.md
          - Compression: api/compression.md
          - Flexure: api/flexure.md
          - Shear: api/shear.md
plugins:
  - mkdocstrings:
      watch:
        - pymechtest
  - search
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
