name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install nox
          python3 -m pip install .[test]

      - name: Run Tests
        run: nox --non-interactive --session "test-${{ matrix.python-version }}"

  conda-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Install Dependencies
        run: |
          conda activate test
          conda install pip setuptools wheel
          conda install -c conda-forge nox

      - name: Run Tests
        run: nox --non-interactive --session "test_conda-${{ matrix.python-version }}"

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install nox
          python3 -m pip install .[lint]

      - name: Lint
        run: nox --non-interactive --session "lint"

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install nox
          python3 -m pip install .[docs]

      - name: Build Docs
        run: nox --non-interactive --session "docs"

  deploy:
    needs: [build, conda-build, lint, docs]
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install setuptools and wheel
        # Uses pypa build https://pypa-build.readthedocs.io/en/latest/
        # For full PEP517/518 compliance
        run: python3 -m pip install --upgrade pip setuptools wheel twine build

      - name: Build sdist and wheel
        run: python3 -m build
      - name: Publish distribution PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
