name: Publish Docs
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install .[docs]

      - name: Deploy Docs to GitHub Pages
        env:
          # Use the built in CI GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add gh-token "https://${GITHUB_TOKEN}@github.com/FollowTheProcess/pymechtest.git";
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
          mkdocs gh-deploy -v --clean --remote-name gh-token;
