name: Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install mkdocs mkdocs-material mkdocstrings
          pip install nox
          pip install .

      - name: Build Docs
        run: |
          nox --non-interactive --session "docs"
